name: Trigger auto deployment for container-app-jgpqppzqh5yr4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-jgpqppzqh5yr4-AutoDeployTrigger-ce3c78a6-f521-4a53-97dd-c14683e8b84d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJGPQPPZQH5YR4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJGPQPPZQH5YR4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJGPQPPZQH5YR4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPJGPQPPZQH5YR4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJGPQPPZQH5YR4_REGISTRY_PASSWORD }}
          containerAppName: container-app-jgpqppzqh5yr4
          resourceGroup: starshotbackendb826
          imageToBuild: default/container-app-jgpqppzqh5yr4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


