name: Trigger auto deployment for container-app-c5g4kcvvswyew

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-c5g4kcvvswyew-AutoDeployTrigger-a5eacfb5-b070-4d33-91fd-8e1050d9e497.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPC5G4KCVVSWYEW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPC5G4KCVVSWYEW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPC5G4KCVVSWYEW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPC5G4KCVVSWYEW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPC5G4KCVVSWYEW_REGISTRY_PASSWORD }}
          containerAppName: container-app-c5g4kcvvswyew
          resourceGroup: starshotbackendb72f
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


