name: Trigger auto deployment for container-app-iro6z7lv4jtii

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-iro6z7lv4jtii-AutoDeployTrigger-814d2302-4db4-4b2a-9bf2-fa23e86595e6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPIRO6Z7LV4JTII_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPIRO6Z7LV4JTII_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPIRO6Z7LV4JTII_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: newftregistry.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPIRO6Z7LV4JTII_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPIRO6Z7LV4JTII_REGISTRY_PASSWORD }}
          containerAppName: container-app-iro6z7lv4jtii
          resourceGroup: starshotbackend9d17
          imageToBuild: newftregistry.azurecr.io/container-app-iro6z7lv4jtii:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


