name: Trigger auto deployment for container-app-oyrcwmpk57z2g

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-oyrcwmpk57z2g-AutoDeployTrigger-480a3684-f83a-4bf7-8fd8-0e3dc98e4b44.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOYRCWMPK57Z2G_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOYRCWMPK57Z2G_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOYRCWMPK57Z2G_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOYRCWMPK57Z2G_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOYRCWMPK57Z2G_REGISTRY_PASSWORD }}
          containerAppName: container-app-oyrcwmpk57z2g
          resourceGroup: starshotbackendaf8c
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


