name: Trigger auto deployment for container-app-by7jtdfvh7agc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-by7jtdfvh7agc-AutoDeployTrigger-cae1ec5e-b9f4-40d5-916c-1ed6b1a013f2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPBY7JTDFVH7AGC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPBY7JTDFVH7AGC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPBY7JTDFVH7AGC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPBY7JTDFVH7AGC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPBY7JTDFVH7AGC_REGISTRY_PASSWORD }}
          containerAppName: container-app-by7jtdfvh7agc
          resourceGroup: starshotbackendae72
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


