name: Trigger auto deployment for defaultstarshotrepo91dba62b

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/defaultstarshotrepo91dba62b-AutoDeployTrigger-7218a3a0-3a09-4d53-9ed4-739b61608c69.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEFAULTSTARSHOTREPO91DBA62B_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEFAULTSTARSHOTREPO91DBA62B_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEFAULTSTARSHOTREPO91DBA62B_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.DEFAULTSTARSHOTREPO91DBA62B_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEFAULTSTARSHOTREPO91DBA62B_REGISTRY_PASSWORD }}
          containerAppName: defaultstarshotrepo91dba62b
          resourceGroup: defaultstarshotrepo91db
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


