name: Trigger auto deployment for starshotbackendae72a094

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/starshotbackendae72a094-AutoDeployTrigger-74f5b495-ceb2-4189-960b-14ee7f4db180.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.STARSHOTBACKENDAE72A094_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STARSHOTBACKENDAE72A094_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STARSHOTBACKENDAE72A094_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.STARSHOTBACKENDAE72A094_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STARSHOTBACKENDAE72A094_REGISTRY_PASSWORD }}
          containerAppName: starshotbackendae72a094
          resourceGroup: starshotbackendae72
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


